// Automatically generated by ch1108.annotations.testcase.TestCaseAnnotationProcessor
package ch1108.annotations.testcase;

  public class FactorialTest  {

    public static void main(String[] args) {
      assert(ch1108.annotations.testcase.Factorial.factorial(0) == 1);
      assert(ch1108.annotations.testcase.Factorial.factorial(3) == 6);
      assert(ch1108.annotations.testcase.Factorial.factorial(4) == 24);
    }

  }
