// Automatically generated by ch1108.annotations.testcase.TestCaseAnnotationProcessor
package ch1108.annotations.testcase;

  public class MyMathTest  {

    public static void main(String[] args) {
      assert(ch1108.annotations.testcase.MyMath.factorial(4) == 24);
      assert(ch1108.annotations.testcase.MyMath.factorial(0) == 1);
      assert(ch1108.annotations.testcase.MyMath.factorial(3) == 6);
      assert(ch1108.annotations.testcase.MyMath.factorial(9) == 362880);
    }

  }
