package ch1108.annotations.testcase;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic.Kind;
import javax.tools.JavaFileObject;

@SupportedAnnotationTypes({"ch1108.annotations.testcase.TestCase","ch1108.annotations.testcase.TestCases"})
@SupportedSourceVersion(SourceVersion.RELEASE_8)
public class TestCaseAnnotationProcessor extends AbstractProcessor {

  private String sourceFQClass = ""; 
  private String sourcePkg = "";
  private String targetFQClass = ""; 
  private String targetClass = "";
  private String funName = "";
 
  @Override
  public boolean process(Set<? extends TypeElement> annotations,
      RoundEnvironment currentRound) {
    if (annotations.size() == 0) return true;

    for (Element e : currentRound.getElementsAnnotatedWith(TestCases.class)) {
      funName = e.getSimpleName().toString();
      sourceFQClass = e.getEnclosingElement().toString(); 
      break;
    }
    
    if (funName.equals(""))
      for (Element e : currentRound.getElementsAnnotatedWith(TestCase.class)) {
        funName = e.getSimpleName().toString();
        sourceFQClass = e.getEnclosingElement().toString();
        break;
      }
 
    sourcePkg = sourceFQClass.replaceFirst("\\.[^.]*$", "");
    targetFQClass = sourceFQClass + "Test";
    targetClass = targetFQClass.replaceFirst(".*\\.", "");
   
    try {
      JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(targetFQClass);

      try (PrintWriter out = new PrintWriter(sourceFile.openWriter())) {
        out.println("// Automatically generated by ch1108.annotations.testcase.TestCaseAnnotationProcessor");
        out.println("package "+sourcePkg+";");
        out.println("\r\n  public class "+targetClass+"  {");
        out.println("\r\n    public static void main(String[] args) {");
              
        for (Element el : currentRound.getElementsAnnotatedWith(TestCase.class)) {
          TestCase[] annos = el.getAnnotationsByType(TestCase.class);
          for (TestCase tc : annos) processElement(el, tc, out);
        }
        
        for (Element el : currentRound.getElementsAnnotatedWith(TestCases.class)) {
          TestCase[] annos = el.getAnnotationsByType(TestCase.class);
          for (TestCase tc : annos) processElement(el, tc, out);
        }
        
        out.println("    }");
        out.println("\r\n  }");
        out.close();
      }
    } catch (IOException ex) {
      processingEnv.getMessager().printMessage(Kind.ERROR, ex.getMessage());
    }        
    return true;
  }
  
  private void processElement(Element el, TestCase anno, PrintWriter out) {
    String[] params = anno.params().split(",");
    String expected = anno.expected(); // assume single valued result
    // output
    StringBuilder builder = new StringBuilder();
    builder.append("      assert("+sourceFQClass+"."+funName+"(");
    for (int i = 0; i < params.length - 1; i ++) {
      builder.append(params[i]+", ");
    }
    builder.append(params[params.length - 1]+") == "+expected+");");
    out.println(builder.toString());    
  } 
  
}
